displayName: "ecom365 maintenance"
type: middleware
import: github.com/jake-bcn/ecom365-maintenance
summary: "ecom365 maintenance"
testData:
  IsEnable: false
  IsWholeSiteMaintenance: false
  FrontendMaintenancePath:    
    - "customer"
  MerchantMaintenance:
    - "demo"
  AdminApiMaintenancePath:    
    - "admin_merchant"
  MerchantApiMaintenancePath:
    - "demo/customer"
    - "demo2/customer"
  ServiceMaintenancePath:
    - "customer"
  IsFrontendBaseMaintenance: false
  IsDebug: false